### ISSUE TITLE
Holding Either The "Menus: Confirm" or "Menus: Back" Binds As Part Of A Controller Bind Causes An Auto Repeat Of The Action

### ISSUE THREAD

**Issue by ZaptorZap** [tetrio/issues#520]
### Checklist (issue will be disregarded & closed if incomplete!)
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.
-----
### Describe the bug/issue
Big title I know, but there's no easy way to compress that. An auto repeat of these binds will either lead to network silliness (e.g. "You are already in this room"), mass openings of the CH.TETR.IO domain, and other general noise disturbances. 
### Reproducing
1. Connect a controller 
1.1. I ended up using bluetooth connections to confirm the issue with three separate controllers: a DualShock4, an XBox One controller, and the Switch Pro Controller.
2. Head to the config and bind any controller button to "Menus: Confirm"/"Menus: Back"
3. Hold the bound button down and see the effects.
### Expected behavior
I suppose I'd expect the menu to only advance one single time, not a thousand. Cap the bind to one action per press n' hold if you can.
### Videos
[Example 1](https://cdn.discordapp.com/attachments/673303546564968566/768666050727903242/22_024355.mp4) : Performing the glitch on the Tetra League worldwide leaderboards. 
[Example 2](https://i.fiery.me/mEV6q.mp4) : Joining a public custom room by holding the A button
[Example 3](https://cdn.discordapp.com/attachments/673303546564968566/768681890352726026/TETR.IO_2020-10-22_03-47-05.mp4) : An attempt to preform #372 from the main menu. Seems I was disconnected before I matched against anyone.
[Example 4](https://cdn.discordapp.com/attachments/673303546564968566/768683261751853096/TETR.IO_2020-10-22_03-52-15.mp4) : Yet *another* attempt to preform #372, this time from the "ENTER MATCHMAKING" screen. 
### Your setup
 - **OS and version**: Windows 10 Version 1903
 - **Browser and version**: Desktop Client V4, Game Verison 5.1.1
### Additional context
This issue was brought to my attention by user "TWITCHY96CAMERA" on the TETR.IO Discord server. [Post viewable here.](https://discord.com/channels/673303546107658242/673305614318960671/767552659853934622)

**Comment by ZaptorZap** [comment]
Yep, the described behavior is still the same, and seemingly hasn't changed since the release of desktop V7, which is where I retested this issue with an Xbox One controller. (felt it was a bit redundant to attempt any of the other controllers)

**Comment by o5k** [comment]
Fixed recently

**Comment by ZaptorZap** [comment]
Still occurs on v6.0.8, exactly as described in the original issue.

**Comment by o5k** [comment]
Fixed in next version.
