### ISSUE TITLE
Wrong level displayed in the upper right corner

### ISSUE THREAD

**Issue by Wirtualnosc** [tetrio/issues#53]
### Description
Your level and experience in upper right corner is not displayed correctly sometimes. It seems to happen because of XP updates when you're out of the game which gives you such.

### Reproduction
- Join a quick lobby and lose
- Immediately leave to main menu
- Wait in main menu until that quick lobby game finishes
- Check your level by any other means (like checking your profile). It will show the correct level and XP, unlike the one in the upper right corner which hasn't updated since.

Any future XP updates will also update that corner display incorrectly.

### Expected behavior
Level and experience in upper right corner always should show the correct value.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/74790462-8279db80-52af-11ea-95e8-b90170cea5aa.png)

### Your setup
Arch Linux 5.5.4-arch1-1 on x86_64 PC, using Firefox 73.0

**Comment by o5k** [comment]
This has been fixed in the coming update.

**Comment by Wirtualnosc** [comment]
still happens in tetra channel when you see yourself 'till you click to look @ profile

**Comment by o5k** [comment]
This is because when you leave early, the XP is not updated locally. You must view your own profile or enter a room to sync them.

**Comment by Wirtualnosc** [comment]
Yeah, I can agree on that much, but since you can see your own player XP through other means (such as tetra channel) and since you receive those through the API too, I believe it would be possible to update it in those circumstances as well.

**Comment by Wirtualnosc** [comment]
![image](https://user-images.githubusercontent.com/6901295/76712461-42bcdd00-6711-11ea-8071-5d71aee6e7aa.png)
this can happen when you leave and rejoin before your XP gets updated. The XP update will never apply to the corner display

and the tetra channel issue I mentioned earlier, which should be possible to update from the user list if your name appears - I mentioned this several times already so I'm not sure if you want to tackle this eventually
![image](https://user-images.githubusercontent.com/6901295/76712490-7ac42000-6711-11ea-86ac-d2181c3ab38f.png)

**Comment by o5k** [comment]
seems this has started popping up again, as well as serverside xp being off (some can enter TL too early/too late)

**Comment by ZaptorZap** [comment]
This still happens often enough from what I've seen.

**Comment by o5k** [comment]
yea i found the cause now, i totally forgot to make it apply solo games' XP immediately

**Comment by o5k** [comment]
Should be fixed in a patch.
