### ISSUE TITLE
loosing TR by winning a game

### ISSUE THREAD

**Issue by suprainfinite** [tetrio/issues#552]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [ X] I am using the **newest version** of TETR.IO.
- [X ] I know **how to reproduce the issue**.
- [X ] I am using a **supported browser** or the Desktop Client.
- [ X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [ X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
after winning my game counter someone,(he was no rank and no TR yet), I have loose 29 TR instead of winning some,

### Reproducing
only playing tetra league, I don't really know how to reproduce it, since it's my frst time ever I found this bug. But the guy I have fiight say he was haking, so propably related or he was just joking, but that an hard coincidence.

### Expected behavior
/

### Your setup
 - **window10
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
![wut](https://user-images.githubusercontent.com/66995468/100457482-6585fa80-30c2-11eb-9bf4-45e11411b38e.PNG)
![wut2](https://user-images.githubusercontent.com/66995468/100457494-6a4aae80-30c2-11eb-87c0-d6bfcde1cf88.PNG)

**Comment by o5k** [comment]
This should be fixed next update (5.2.0), let me know if it isn't.

**Comment by ZaptorZap** [comment]
Seems like the bug is still happening. [As reported by Santiago#6916 on the official TETR.IO Discord server,](https://discord.com/channels/673303546107658242/673303546564968566/790403734915383297) user [NETRI](https://ch.tetr.io/u/netri) encountered the original bug described on 5.2.1
![image](https://cdn.discordapp.com/attachments/673303546564968566/790403733082734652/unknown-2.png)
![image](https://cdn.discordapp.com/attachments/673303546564968566/790404497339449377/unknown.png)

**Comment by 0x3d6** [comment]
I had this happen, too, yesterday:
![](https://i.imgur.com/LwIj7GE.png)

**Comment by octomistic** [comment]
<img width="1440" alt="Screen Shot 2020-12-26 at 1 14 05 AM" src="https://user-images.githubusercontent.com/76608626/103146611-39d64e80-471a-11eb-8687-e57b9adec80e.png">

Happened today, desktop mac up to date. However, it is unclear to me if it actually went down or is just appearing to have. I am not sure of my score before this game exactly but it is possible from looking at it that it may have actually increased and just displayed wrong.

**Comment by o5k** [comment]
Fixed in next patch.
