### ISSUE TITLE
Dim/Invisible B2B indicator if B2B increases quickly after B2B level up

### ISSUE THREAD

**Issue by Ecpii** [tetrio/issues#824]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop App

### Describe the bug/issue

The B2B indicator appears in a dim color, or not at all in Zen mode. Upon increasing B2B level (x3-x7 -> x8), the indicator corrected itself. However, after breaking B2B and building another chain, the indicator is not present at all, even on changing B2B level. On breaking this invisible B2B chain, the indicator flashes "B2B x0".

### Expected behavior

The B2B meter remains bright gold/yellow and flashes on level up. It is present for all B2B levels starting from x1, even after B2B is broken and built again. Breaking a B2B chain should flash the indicator red with the number showing how long the chain was.

### Screenshots

https://youtu.be/CKoTm2TeaYU

### Console logs

![TETR IO_2021-11-14_17-45-31](https://user-images.githubusercontent.com/28408948/141702281-10a6789b-fbea-4e58-b60c-28906d0c1fcf.png)

### Additional context

This occurred on the first instance of playing the game; I opened the game and this Zen session was the first thing I did.

[config.ttc.txt](https://github.com/tetrio/issues/files/7534898/config.ttc.txt)

**Comment by TetrioStuff** [comment]
It still happens, just a result of increasing b2b while it is still flashing from level increase (x1, X3, x8, x24)

**Comment by orangetriangle** [comment]
This is still a problem; see, e.g. [dtq.zip](https://github.com/tetrio/issues/files/9273777/dtq.zip) round 8, time 0:43.133. I suggest reopening this issue.

![image](https://user-images.githubusercontent.com/77557642/183217896-fbedbde5-8835-419e-a2c5-e8383633d046.png)

**Comment by Dimentio** [comment]
Fixed in next update!

**Comment by BaronAWC95014** [comment]
<img width="653" alt="Screen Shot 2022-12-02 at 5 22 41 PM" src="https://user-images.githubusercontent.com/43506286/205415699-5dfc99fe-5ac1-46c5-9867-f35efb705f81.png">
i still have this bug occurring. i managed to get the dim b2b counter by completing a t-spin as the b2b meter was flashing the b2b x 3 (it doesn't seem to happen every time).

**Comment by MESIR1** [comment]
Still occurs

**Comment by Ecpii** [comment]
https://github.com/tetrio/issues/assets/28408948/e29bc8a6-a280-4951-9dae-e19e494f58f3

Still happens as of today (2023-06-01)

**Comment by Ecpii** [comment]
https://github.com/tetrio/issues/assets/28408948/3ff364d7-fb4d-46dd-b3f1-caa27e61c6c5

Still happens as of 2023-09-17
